version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  my-orb: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - my-orb/greet
workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: ericribeiro/my-orb
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publisher
          filters: *release-filters
