version: 2.1
orbs:
  my-pkg-app: ericribeiro/my-pkg-app@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  pack-scripts:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run: 
          name: Package the scripts
          command: |
            source src/scripts/utils.sh
            detect-os
            for script in src/scripts/*.js; do 
              if [ "$PLATFORM" = "linux" ]; then
                npx pkg "$script" --target latest-linux-x64
              elif [ "$PLATFORM" = "macos" ]; then
                npx pkg "$script" --target latest-macos-x64
              elif [ "$PLATFORM" = "windows" ]; then
                npx pkg "$script" --target latest-win-x64
              elif [ "$PLATFORM" = "alpine" ]; then
                npx pkg "$script" --target latest-alpine-x64
              fi
            done
      - persist_to_workspace:
          root: .

  run-scripts:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - my-pkg-app/greet

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - pack-scripts:
          filters: *filters
      - run-scripts:
          filters: *filters
          requires:
            - pack-scripts
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: ericribeiro/my-pkg-app
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
